jwt:
  header: Authorization
  secret: giong-@uthorization-2016
logging:
  level:
    org.springframework.security: debug
    org.hibernate.SQL: trace
server:
  port: 8080
spring:
  resources:
    chain:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leave_application_db?autoReconnect=true&useSSL=false
    username: admin
    password: r000000t
    continue-on-error: true
    tomcat:
      max-active: 50
      test-on-borrow: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  security:
    enabled: true
debug: true
